application: waldo-gcp
module: optimal-waypoints
version: 1
runtime: custom
api_version: 1
threadsafe: yes
vm: true

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: .5
  memory_gb: 1.3

handlers:

- url: /.*
  script: main.app


